; Listing generated by Microsoft (R) Optimizing Compiler Version 19.21.27702.2 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG132518 DB	'D:\Qt\5.12.5\msvc2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG132519 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG132520 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG135482 DB	'D:\Qt\5.12.5\msvc2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG135483 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG135484 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG135843 DB	'D:\Qt\5.12.5\msvc2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG135844 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG135845 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG136204 DB	'D:\Qt\5.12.5\msvc2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG136205 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG136206 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
?qt_meta_stringdata_DesktopApp@@3Uqt_meta_stringdata_DesktopApp_t@@B DD 0ffffffffH ; qt_meta_stringdata_DesktopApp
	DD	0aH
	DD	00H
	ORG $+4
	DQ	0000000000000090H
	DD	0ffffffffH
	DD	04H
	DD	00H
	ORG $+4
	DQ	0000000000000083H
	DD	0ffffffffH
	DD	00H
	DD	00H
	ORG $+4
	DQ	0000000000000070H
	DD	0ffffffffH
	DD	015H
	DD	00H
	ORG $+4
	DQ	0000000000000059H
	DD	0ffffffffH
	DD	016H
	DD	00H
	ORG $+4
	DQ	0000000000000057H
	DD	0ffffffffH
	DD	014H
	DD	00H
	ORG $+4
	DQ	0000000000000056H
	DB	044H
	DB	065H
	DB	073H
	DB	06bH
	DB	074H
	DB	06fH
	DB	070H
	DB	041H
	DB	070H
	DB	070H
	DB	00H
	DB	065H
	DB	078H
	DB	069H
	DB	074H
	DB	00H
	DB	00H
	DB	06fH
	DB	06eH
	DB	05fH
	DB	063H
	DB	06cH
	DB	069H
	DB	063H
	DB	06bH
	DB	065H
	DB	064H
	DB	05fH
	DB	074H
	DB	065H
	DB	06dH
	DB	070H
	DB	042H
	DB	075H
	DB	074H
	DB	074H
	DB	06fH
	DB	06eH
	DB	00H
	DB	06fH
	DB	06eH
	DB	05fH
	DB	063H
	DB	06cH
	DB	069H
	DB	063H
	DB	06bH
	DB	065H
	DB	064H
	DB	05fH
	DB	06cH
	DB	069H
	DB	067H
	DB	068H
	DB	074H
	DB	042H
	DB	075H
	DB	074H
	DB	074H
	DB	06fH
	DB	06eH
	DB	00H
	DB	06fH
	DB	06eH
	DB	05fH
	DB	063H
	DB	06cH
	DB	069H
	DB	063H
	DB	06bH
	DB	065H
	DB	064H
	DB	05fH
	DB	068H
	DB	075H
	DB	06dH
	DB	042H
	DB	075H
	DB	074H
	DB	074H
	DB	06fH
	DB	06eH
	DB	00H
	ORG $+5
	ORG $+8
?qt_meta_data_DesktopApp@@3QBIB DD 08H			; qt_meta_data_DesktopApp
	DD	00H
	DD	00H
	DD	00H
	DD	04H
	DD	0eH
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	00H
	DD	022H
	DD	02H
	DD	08H
	DD	03H
	DD	00H
	DD	023H
	DD	02H
	DD	08H
	DD	04H
	DD	00H
	DD	024H
	DD	02H
	DD	08H
	DD	05H
	DD	00H
	DD	025H
	DD	02H
	DD	08H
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	00H
CONST	ENDS
PUBLIC	?__empty_global_delete@@YAXPEAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPEAX_K@Z		; __empty_global_delete
PUBLIC	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
PUBLIC	?metaObject@DesktopApp@@UEBAPEBUQMetaObject@@XZ	; DesktopApp::metaObject
PUBLIC	?qt_metacast@DesktopApp@@UEAAPEAXPEBD@Z		; DesktopApp::qt_metacast
PUBLIC	?qt_metacall@DesktopApp@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ; DesktopApp::qt_metacall
PUBLIC	?qt_static_metacall@DesktopApp@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; DesktopApp::qt_static_metacall
PUBLIC	?staticMetaObject@DesktopApp@@2UQMetaObject@@B	; DesktopApp::staticMetaObject
EXTRN	strcmp:PROC
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ:PROC
EXTRN	__imp_?qt_metacast@QMainWindow@@UEAAPEAXPEBD@Z:PROC
EXTRN	__imp_?qt_metacall@QMainWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z:PROC
EXTRN	?exit@DesktopApp@@AEAAXXZ:PROC			; DesktopApp::exit
EXTRN	?on_clicked_tempButton@DesktopApp@@AEAAXXZ:PROC	; DesktopApp::on_clicked_tempButton
EXTRN	?on_clicked_lightButton@DesktopApp@@AEAAXXZ:PROC ; DesktopApp::on_clicked_lightButton
EXTRN	?on_clicked_humButton@DesktopApp@@AEAAXXZ:PROC	; DesktopApp::on_clicked_humButton
EXTRN	__imp_?staticMetaObject@QMainWindow@@2UQMetaObject@@B:BYTE
_BSS	SEGMENT
?staticMetaObject@DesktopApp@@2UQMetaObject@@B DB 030H DUP (?) ; DesktopApp::staticMetaObject
_BSS	ENDS
pdata	SEGMENT
$pdata$?metaObject@DesktopApp@@UEBAPEBUQMetaObject@@XZ DD imagerel $LN5
	DD	imagerel $LN5+88
	DD	imagerel $unwind$?metaObject@DesktopApp@@UEBAPEBUQMetaObject@@XZ
$pdata$?qt_metacast@DesktopApp@@UEAAPEAXPEBD@Z DD imagerel $LN5
	DD	imagerel $LN5+75
	DD	imagerel $unwind$?qt_metacast@DesktopApp@@UEAAPEAXPEBD@Z
$pdata$?qt_metacall@DesktopApp@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN9
	DD	imagerel $LN9+174
	DD	imagerel $unwind$?qt_metacall@DesktopApp@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
$pdata$?qt_static_metacall@DesktopApp@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN11
	DD	imagerel $LN11+129
	DD	imagerel $unwind$?qt_static_metacall@DesktopApp@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z
pdata	ENDS
CRT$XCU	SEGMENT
??staticMetaObject$initializer$@DesktopApp@@2P6AXXZEA@@3P6AXXZEA DQ FLAT:??__E?staticMetaObject@DesktopApp@@2UQMetaObject@@B@@YAXXZ ; ??staticMetaObject$initializer$@DesktopApp@@2P6AXXZEA@@3P6AXXZEA
CRT$XCU	ENDS
xdata	SEGMENT
$unwind$?metaObject@DesktopApp@@UEBAPEBUQMetaObject@@XZ DD 010901H
	DD	06209H
$unwind$?qt_metacast@DesktopApp@@UEAAPEAXPEBD@Z DD 010e01H
	DD	0420eH
$unwind$?qt_metacall@DesktopApp@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	04217H
$unwind$?qt_static_metacall@DesktopApp@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	06217H
xdata	ENDS
; Function compile flags: /Odtp
;	COMDAT ??__E?staticMetaObject@DesktopApp@@2UQMetaObject@@B@@YAXXZ
text$di	SEGMENT
??__E?staticMetaObject@DesktopApp@@2UQMetaObject@@B@@YAXXZ PROC ; `dynamic initializer for 'DesktopApp::staticMetaObject'', COMDAT
; File D:\Kasia\BMS\DesktopApp\DesktopApp\x64\Debug\moc\moc_DesktopApp.cpp
; Line 92
	mov	rax, QWORD PTR __imp_?staticMetaObject@QMainWindow@@2UQMetaObject@@B
	mov	QWORD PTR ?staticMetaObject@DesktopApp@@2UQMetaObject@@B, rax
; Line 93
	lea	rax, OFFSET FLAT:?qt_meta_stringdata_DesktopApp@@3Uqt_meta_stringdata_DesktopApp_t@@B
	mov	QWORD PTR ?staticMetaObject@DesktopApp@@2UQMetaObject@@B+8, rax
; Line 94
	lea	rax, OFFSET FLAT:?qt_meta_data_DesktopApp@@3QBIB
	mov	QWORD PTR ?staticMetaObject@DesktopApp@@2UQMetaObject@@B+16, rax
; Line 95
	lea	rax, OFFSET FLAT:?qt_static_metacall@DesktopApp@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; DesktopApp::qt_static_metacall
	mov	QWORD PTR ?staticMetaObject@DesktopApp@@2UQMetaObject@@B+24, rax
; Line 96
	mov	QWORD PTR ?staticMetaObject@DesktopApp@@2UQMetaObject@@B+32, 0
; Line 97
	mov	QWORD PTR ?staticMetaObject@DesktopApp@@2UQMetaObject@@B+40, 0
	ret	0
??__E?staticMetaObject@DesktopApp@@2UQMetaObject@@B@@YAXXZ ENDP ; `dynamic initializer for 'DesktopApp::staticMetaObject''
text$di	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv69 = 32
_t$1 = 40
_o$ = 64
_c$ = 72
_id$ = 80
_a$ = 88
?qt_static_metacall@DesktopApp@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z PROC ; DesktopApp::qt_static_metacall
; File D:\Kasia\BMS\DesktopApp\DesktopApp\x64\Debug\moc\moc_DesktopApp.cpp
; Line 76
$LN11:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 77
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN4@qt_static_
; Line 78
	mov	rax, QWORD PTR _o$[rsp]
	mov	QWORD PTR _t$1[rsp], rax
; Line 80
	mov	eax, DWORD PTR _id$[rsp]
	mov	DWORD PTR tv69[rsp], eax
	cmp	DWORD PTR tv69[rsp], 0
	je	SHORT $LN5@qt_static_
	cmp	DWORD PTR tv69[rsp], 1
	je	SHORT $LN6@qt_static_
	cmp	DWORD PTR tv69[rsp], 2
	je	SHORT $LN7@qt_static_
	cmp	DWORD PTR tv69[rsp], 3
	je	SHORT $LN8@qt_static_
	jmp	SHORT $LN9@qt_static_
$LN5@qt_static_:
; Line 81
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?exit@DesktopApp@@AEAAXXZ		; DesktopApp::exit
	jmp	SHORT $LN2@qt_static_
$LN6@qt_static_:
; Line 82
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?on_clicked_tempButton@DesktopApp@@AEAAXXZ ; DesktopApp::on_clicked_tempButton
	jmp	SHORT $LN2@qt_static_
$LN7@qt_static_:
; Line 83
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?on_clicked_lightButton@DesktopApp@@AEAAXXZ ; DesktopApp::on_clicked_lightButton
	jmp	SHORT $LN2@qt_static_
$LN8@qt_static_:
; Line 84
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?on_clicked_humButton@DesktopApp@@AEAAXXZ ; DesktopApp::on_clicked_humButton
$LN9@qt_static_:
$LN2@qt_static_:
$LN4@qt_static_:
; Line 89
	add	rsp, 56					; 00000038H
	ret	0
?qt_static_metacall@DesktopApp@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ENDP ; DesktopApp::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_c$ = 56
_id$ = 64
_a$ = 72
?qt_metacall@DesktopApp@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z PROC ; DesktopApp::qt_metacall
; File D:\Kasia\BMS\DesktopApp\DesktopApp\x64\Debug\moc\moc_DesktopApp.cpp
; Line 115
$LN9:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 116
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacall@QMainWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
	mov	DWORD PTR _id$[rsp], eax
; Line 117
	cmp	DWORD PTR _id$[rsp], 0
	jge	SHORT $LN2@qt_metacal
; Line 118
	mov	eax, DWORD PTR _id$[rsp]
	jmp	SHORT $LN1@qt_metacal
$LN2@qt_metacal:
; Line 119
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN3@qt_metacal
; Line 120
	cmp	DWORD PTR _id$[rsp], 4
	jge	SHORT $LN5@qt_metacal
; Line 121
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	?qt_static_metacall@DesktopApp@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; DesktopApp::qt_static_metacall
$LN5@qt_metacal:
; Line 122
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 4
	mov	DWORD PTR _id$[rsp], eax
	jmp	SHORT $LN4@qt_metacal
$LN3@qt_metacal:
; Line 123
	cmp	DWORD PTR _c$[rsp], 12
	jne	SHORT $LN6@qt_metacal
; Line 124
	cmp	DWORD PTR _id$[rsp], 4
	jge	SHORT $LN7@qt_metacal
; Line 125
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	DWORD PTR [rax], -1
$LN7@qt_metacal:
; Line 126
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 4
	mov	DWORD PTR _id$[rsp], eax
$LN6@qt_metacal:
$LN4@qt_metacal:
; Line 128
	mov	eax, DWORD PTR _id$[rsp]
$LN1@qt_metacal:
; Line 129
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacall@DesktopApp@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ENDP ; DesktopApp::qt_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_clname$ = 56
?qt_metacast@DesktopApp@@UEAAPEAXPEBD@Z PROC		; DesktopApp::qt_metacast
; File D:\Kasia\BMS\DesktopApp\DesktopApp\x64\Debug\moc\moc_DesktopApp.cpp
; Line 107
$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 108
	cmp	QWORD PTR _clname$[rsp], 0
	jne	SHORT $LN2@qt_metacas
	xor	eax, eax
	jmp	SHORT $LN1@qt_metacas
$LN2@qt_metacas:
; Line 109
	lea	rdx, OFFSET FLAT:?qt_meta_stringdata_DesktopApp@@3Uqt_meta_stringdata_DesktopApp_t@@B+144
	mov	rcx, QWORD PTR _clname$[rsp]
	call	strcmp
	test	eax, eax
	jne	SHORT $LN3@qt_metacas
; Line 110
	mov	rax, QWORD PTR this$[rsp]
	jmp	SHORT $LN1@qt_metacas
$LN3@qt_metacas:
; Line 111
	mov	rdx, QWORD PTR _clname$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacast@QMainWindow@@UEAAPEAXPEBD@Z
$LN1@qt_metacas:
; Line 112
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacast@DesktopApp@@UEAAPEAXPEBD@Z ENDP		; DesktopApp::qt_metacast
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv82 = 32
this$ = 64
?metaObject@DesktopApp@@UEBAPEBUQMetaObject@@XZ PROC	; DesktopApp::metaObject
; File D:\Kasia\BMS\DesktopApp\DesktopApp\x64\Debug\moc\moc_DesktopApp.cpp
; Line 102
$LN5:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 103
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	cmp	QWORD PTR [rax+40], 0
	je	SHORT $LN3@metaObject
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	mov	rcx, rax
	call	QWORD PTR __imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ
	mov	QWORD PTR tv82[rsp], rax
	jmp	SHORT $LN4@metaObject
$LN3@metaObject:
	lea	rax, OFFSET FLAT:?staticMetaObject@DesktopApp@@2UQMetaObject@@B ; DesktopApp::staticMetaObject
	mov	QWORD PTR tv82[rsp], rax
$LN4@metaObject:
	mov	rax, QWORD PTR tv82[rsp]
; Line 104
	add	rsp, 56					; 00000038H
	ret	0
?metaObject@DesktopApp@@UEBAPEBUQMetaObject@@XZ ENDP	; DesktopApp::metaObject
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ
_TEXT	SEGMENT
this$ = 8
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; File D:\Qt\5.12.5\msvc2017_64\include\QtCore\qscopedpointer.h
; Line 117
	mov	QWORD PTR [rsp+8], rcx
; Line 118
	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
; Line 119
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX_K@Z
_TEXT	SEGMENT
__formal$ = 8
__formal$ = 16
?__empty_global_delete@@YAXPEAX_K@Z PROC		; __empty_global_delete, COMDAT
; File D:\Kasia\BMS\DesktopApp\DesktopApp\x64\Debug\moc\moc_DesktopApp.cpp
; Line 132
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX_K@Z ENDP		; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX@Z
_TEXT	SEGMENT
__formal$ = 8
?__empty_global_delete@@YAXPEAX@Z PROC			; __empty_global_delete, COMDAT
; File D:\Kasia\BMS\DesktopApp\DesktopApp\x64\Debug\moc\moc_DesktopApp.cpp
; Line 132
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
